version: '2'

services:
  apitransfermoney_php:
    container_name: apitransfermoney_php
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
#      - "443:443"
    volumes:
      - .:/var/www/html/


  db:
    image: mysql:latest
    container_name: apitransfermoney_mysql
#    ports:
#      - "3307:3306"
    volumes:
      - /var/libs/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Angelica@1714
