version: '2'

services:
  apitransfermoney2_php:
    image: php:7.4-apache
    container_name: apitransfermoney2_php
    ports:
      - "8080:8080"
#      - "443:443"
    volumes:
      - /home/bueno/Projetos/apiTransferMoney2:/var/www/html/
    links:
      - db

  db:
    image: mysql:latest
    container_name: apiTransferMoney2_mysql
#    ports:
#      - "3307:3306"
    volumes:
      - /var/libs/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Angelica@1714
